//==============================================================================
//
//  OvenMediaEngine
//
//  Created by Hyunjun Jang
//  Copyright (c) 2018 AirenSoft. All rights reserved.
//
//==============================================================================
#pragma once

#include <base/ovlibrary/ovlibrary.h>
#include <openssl/ec.h>
#include <openssl/ssl.h>
#include <openssl/store.h>

#include "base/common_types.h"
#include "openssl/openssl_error.h"

#define CERT_NAME "OME"

static const int DefaultCertificateLifetimeInSeconds = 60 * 60 * 24 * 30 * 12;	// 1 years
static const int CertificateWindowInSeconds = -60 * 60 * 24;

enum class KeyType : int32_t
{
	Rsa,
	Ecdsa,
	Last,

	Default = static_cast<int>(Ecdsa)
};

class Certificate
{
public:
	Certificate() = default;
	explicit Certificate(X509 *cert);
	~Certificate();

	// Gemerate a certificate
	std::shared_ptr<ov::OpensslError> Generate();
	//
	// Generate a certificate from a PEM file
	//
	// chain_cert_filename is optional
	std::shared_ptr<ov::OpensslError> GenerateFromPem(
		const char *private_key_filename,
		const char *cert_filename,
		const char *chain_cert_filename);

	// If generated by GenerateFromPem(), returns the file name at the time of creation. If generated by Generate(), returns nullptr
	EVP_PKEY *GetPrivateKey() const;
	const char *GetPrivateKeyPath() const
	{
		return (_private_key != nullptr) ? _private_key_filename.CStr() : nullptr;
	}

	// If generated by GenerateFromPem(), returns the file name at the time of creation. If generated by Generate(), returns nullptr
	X509 *GetCertification() const;
	const char *GetCertificationPath() const
	{
		return (_certificate != nullptr) ? _certificate_filename.CStr() : nullptr;
	}

	// If generated by GenerateFromPem(), returns the file name at the time of creation. If generated by Generate(), returns nullptr
	STACK_OF(X509) * GetChainCertification() const;
	const char *GetChainCertificationPath() const
	{
		return (_chain_certificate != nullptr) ? _chain_certificate_filename.CStr() : nullptr;
	}

	ov::String GetFingerprint(const ov::String &algorithm);

	// Print Cert for Test
	void Print();

private:
	// Number of supported hash algorithms for the `GetFingerprint` cache.
	// See `FingerprintSlot`/`AlgorithmToIndex` below for the slot layout.
	static constexpr size_t FINGERPRINT_ALGORITHM_COUNT = 6;

	enum class LoadType
	{
		None = 0,
		Pkey = OSSL_STORE_INFO_PKEY,
		Cert = OSSL_STORE_INFO_CERT,
	};

	// Per-algorithm fingerprint cache.
	// Each supported hash gets its own slot so that the `algorithm` argument is honored
	// (no master-parity silent override) while keeping the post-warmup fast path lock-free.
	//
	// Slot index assignment (see `AlgorithmToIndex`):
	//   0: md5, 1: sha-1, 2: sha-224, 3: sha-256, 4: sha-384, 5: sha-512.
	//
	// Lifecycle of a single slot:
	//   - `ready=false`
	//     slot is empty; the first `GetFingerprint(algorithm)` that hits
	//     this slot enters the slow path under `_digest_mutex`, computes the digest,
	//     formats the hex string into `fingerprint`, then `ready.store(true, release)`.
	//   - `ready=true`
	//     `fingerprint` is immutable for the lifetime of the Certificate.
	//     Subsequent reads use `ready.load(acquire)` and return `fingerprint` without
	//     touching the mutex.
	struct FingerprintSlot
	{
		std::atomic<bool> ready{false};
		ov::String fingerprint;
	};

private:
	static void X509StackFree(STACK_OF(X509) * instance)
	{
		::sk_X509_pop_free(instance, ::X509_free);
	}

	template <typename T>
	static ov::RaiiPtr<T> LoadPem(
		const LoadType type,
		const char *pem_file,
		T *initial_value,
		const std::function<T *(int type, const OSSL_STORE_INFO *info, T *previous_value)> &handler,
		std::function<void(T *instance)> deleter)
	{
		auto store_ctx = ov::RaiiPtr<OSSL_STORE_CTX>(
			::OSSL_STORE_open(pem_file, nullptr, nullptr, nullptr, nullptr),
			::OSSL_STORE_close);

		if (store_ctx == nullptr)
		{
			return {nullptr, deleter};
		}

		if (type != LoadType::None)
		{
			// Filter by type
			if (::OSSL_STORE_expect(store_ctx, static_cast<int>(type)) == 0)
			{
				return {nullptr, deleter};
			}
		}

		T *instance = initial_value;

		while (::OSSL_STORE_eof(store_ctx) == 0)
		{
			auto info = ov::RaiiPtr<OSSL_STORE_INFO>(
				::OSSL_STORE_load(store_ctx),
				::OSSL_STORE_INFO_free);

			if (info == nullptr)
			{
				// The file includes multiple types of things
				continue;
			}

			instance = handler(::OSSL_STORE_INFO_get_type(info), info, instance);
		}

		return {instance, deleter};
	}

	static ov::RaiiPtr<EVP_PKEY> LoadPrivateKey(const char *pem_file);
	static ov::RaiiPtr<X509> LoadCertificate(const char *pem_file);
	static ov::RaiiPtr<STACK_OF(X509)> LoadChainCertificate(const char *pem_file);

private:
	// Make ECDSA Key
	EVP_PKEY *MakeKey();

	// Make Self-Signed Certificate
	X509 *MakeCertificate(EVP_PKEY *pkey);

	// Computes the raw digest bytes for `algorithm` and appends them to `out_digest`.
	// Returns `false` if the algorithm is unsupported or `X509_digest` fails.
	bool ComputeDigest(const ov::String &algorithm, ov::Data &out_digest);

	bool GetDigestEVP(const ov::String &algorithm, const EVP_MD **mdp);

	static int AlgorithmToIndex(const ov::String &algorithm);

	// Private key
	ov::RaiiPtr<EVP_PKEY> _private_key{nullptr, ::EVP_PKEY_free};
	ov::String _private_key_filename;
	// Certificate
	ov::RaiiPtr<X509> _certificate{nullptr, ::X509_free};
	ov::String _certificate_filename;
	// Chain Certificate(s)
	ov::RaiiPtr<STACK_OF(X509)> _chain_certificate{nullptr, X509StackFree};
	ov::String _chain_certificate_filename;

	// Serializes slow-path digest computation across all slots. A single mutex (rather
	// than per-slot) keeps the memory footprint small; since each slot warms up only
	// once, contention is bounded by the number of distinct algorithms ever requested
	// (typically 1-2 per Certificate instance).
	ov::Mutex _digest_mutex;
	FingerprintSlot _fingerprint_slots[FINGERPRINT_ALGORITHM_COUNT];
};
